#!/bin/bash

echo "Setting up a new Git Repo"

read -p "What is the name of your Repo?" repo
echo "# $repo" >> README.md
git init
git add README.md
git commit -m "first commit"
git branch -M main
git remote add origin git@github.com:Reparo-Ruby/$repo.git
git push -u origin main